# Generated by Django 5.0.14 on 2026-08-30 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_phone', models.CharField(max_length=15)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(help_text='Full name of the screen/module (e.g., Sales Order Entry)', max_length=150, unique=True, verbose_name='Screen Name')),
                ('screen_code', models.CharField(help_text='Short code for the screen (e.g., SO-001)', max_length=50, unique=True, verbose_name='Screen Code')),
                ('screen_type', models.CharField(choices=[('ALL', 'General'), ('ENTRY', 'Data Entry'), ('CONFIGURATION', 'Configuration'), ('QUERY', 'Report/Query')], default='ALL', help_text='The category of the screen', max_length=20, verbose_name='Screen Type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Screen Master',
                'verbose_name_plural': 'Screen Masters',
                'ordering': ['screen_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_assign_ticket', models.BooleanField(default=False, help_text='Enable if this employee can be assigned tickets to other employees', verbose_name='Can Assign Tickets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.department')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.unit')),
            ],
            options={
                'verbose_name': 'Employee Master',
                'verbose_name_plural': 'Employee Masters',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by_name', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('TOGGLE', 'Toggled'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('setting_type', models.CharField(choices=[('UNIT', 'Unit'), ('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee'), ('CREDENTIAL', 'Credential'), ('CONTACT', 'Contact'), ('EMAIL', 'Email'), ('PASSWORD', 'Password'), ('SCREEN', 'Screen'), ('GENERAL', 'General')], max_length=20)),
                ('setting_name', models.CharField(max_length=200)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings Audit Log',
                'verbose_name_plural': 'Settings Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('screen_number', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('error_type', models.CharField(choices=[('New', 'New'), ('Repeated', 'Repeated')], default='New', max_length=50, verbose_name='Error Type')),
                ('main_error_type', models.CharField(blank=True, choices=[('Roadmap Error', 'Roadmap Error'), ('GPL Error', 'GPL Error')], help_text='Select the main error category when closing the ticket', max_length=50, null=True, verbose_name='Main Error Type')),
                ('sub_error_type', models.CharField(blank=True, help_text='Select the sub-error type based on the main error category', max_length=100, null=True, verbose_name='Sub Error Type')),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Assigned', 'Assigned'), ('Hold', 'Hold'), ('Escalated', 'Escalated'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_by_role', models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=10)),
                ('admin_creation_reason', models.CharField(blank=True, choices=[('Phone Call', 'Phone Call'), ('Walk-in Support', 'Walk-in Support'), ('Manager Request', 'Manager Request'), ('Email Forwarded', 'Email Forwarded'), ('Other', 'Other')], max_length=50, null=True)),
                ('assigned_person', models.CharField(blank=True, max_length=100, null=True)),
                ('hold_reason', models.TextField(blank=True, null=True)),
                ('closing_remarks', models.TextField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_viewed', models.BooleanField(default=False, help_text='Admin has viewed this ticket')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When the ticket was first viewed by admin', null=True)),
                ('notification_sent', models.BooleanField(default=False, help_text='Notification email has been sent to admin')),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.department')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ReopenAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/reopen/')),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_attachments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('reports', models.JSONField(default=list)),
                ('frequency', models.JSONField(default=list)),
                ('send_time', models.TimeField(default='08:00')),
                ('send_unit_heads', models.BooleanField(default=True)),
                ('send_admins', models.BooleanField(default=True)),
                ('additional_emails', models.TextField(blank=True, default='')),
                ('all_units', models.BooleanField(default=True)),
                ('subject_template', models.CharField(default='Ticket Report - {{date}}', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('units', models.ManyToManyField(blank=True, related_name='email_schedules', to='tickets.unit')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.unit'),
        ),
        migrations.CreateModel(
            name='UnitHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='tickets.unit')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_head_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ERPHolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_user_id', models.CharField(db_index=True, help_text='ERP User ID (e.g., 0001, 0002, HRD1223)', max_length=50, verbose_name='ERP User ID')),
                ('is_mapped', models.BooleanField(default=False, help_text='True if this ERP ID is mapped to an employee', verbose_name='Is Mapped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee mapped to this ERP User ID (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_mappings', to='tickets.employeemaster', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'ERP User ID',
                'verbose_name_plural': 'ERP User IDs',
                'ordering': ['erp_user_id'],
                'indexes': [models.Index(fields=['erp_user_id'], name='tickets_erp_erp_use_ddb6fb_idx'), models.Index(fields=['employee'], name='tickets_erp_employe_b4edd0_idx'), models.Index(fields=['is_mapped'], name='tickets_erp_is_mapp_c70d3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreenMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_user_id', models.CharField(db_index=True, help_text='ERP User ID (links to ERPHolderMapping.erp_user_id)', max_length=50, verbose_name='ERP User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_mappings', to='tickets.screenmaster', verbose_name='Screen')),
            ],
            options={
                'verbose_name': 'Screen Mapping',
                'verbose_name_plural': 'Screen Mappings',
                'ordering': ['erp_user_id', 'screen__screen_name'],
                'indexes': [models.Index(fields=['erp_user_id'], name='tickets_scr_erp_use_e7c18a_idx'), models.Index(fields=['screen'], name='tickets_scr_screen__914ef2_idx')],
                'unique_together': {('screen', 'erp_user_id')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.department')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.unit')),
            ],
            options={
                'verbose_name': 'Department Credential',
                'verbose_name_plural': 'Department Credentials',
                'ordering': ['unit__code', 'department__name'],
                'unique_together': {('unit', 'department')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('unit', 'name')},
        ),
    ]
