# Generated by Django 5.0.14 on 2026-08-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='target_date',
            field=models.DateField(blank=True, help_text='Expected completion date for the ticket', null=True, verbose_name='Target Date'),
        ),
    ]
