# Generated by Django 5.0.14 on 2026-06-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='error_type',
            field=models.CharField(choices=[('New', 'New'), ('Regular', 'Regular'), ('No Idea', 'No Idea'), ('ERP Error', 'ERP Error'), ('Data Entry Error', 'Data Entry Error'), ('DB Error', 'DB Error'), ('Server Error', 'Server Error'), ('IT Error', 'IT Error'), ('User Error', 'User Error'), ('Other', 'Other')], max_length=50),
        ),
    ]
