# Generated by Django 5.0.14 on 2026-07-24 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_error_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('ASSIGN', 'Assign'), ('HOLD', 'Hold'), ('ESCALATE', 'Escalate'), ('CLOSE', 'Close'), ('REOPEN', 'Reopen'), ('EXPORT', 'Export'), ('SETTINGS_CHANGE', 'Settings Change'), ('PASSWORD_CHANGE', 'Password Change'), ('USER_CREATE', 'User Create'), ('USER_UPDATE', 'User Update'), ('USER_DELETE', 'User Delete'), ('UNIT_CREATE', 'Unit Create'), ('UNIT_UPDATE', 'Unit Update'), ('UNIT_DELETE', 'Unit Delete'), ('DEPARTMENT_CREATE', 'Department Create'), ('DEPARTMENT_UPDATE', 'Department Update'), ('DEPARTMENT_DELETE', 'Department Delete'), ('EMAIL_ADD', 'Email Add'), ('EMAIL_DELETE', 'Email Delete'), ('CONTACT_UPDATE', 'Contact Update'), ('ERROR_TYPE_CREATE', 'Error Type Create'), ('ERROR_TYPE_UPDATE', 'Error Type Update'), ('ERROR_TYPE_DELETE', 'Error Type Delete'), ('BULK_ACTION', 'Bulk Action')], db_index=True, max_length=50)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='tickets_aud_user_id_3642ec_idx'), models.Index(fields=['action', 'timestamp'], name='tickets_aud_action_61f197_idx'), models.Index(fields=['module', 'timestamp'], name='tickets_aud_module_c31ee3_idx')],
            },
        ),
    ]
