# Generated by Django 5.0.14 on 2026-09-11 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sub_error_type',
            field=models.CharField(blank=True, help_text='Select the sub error type based on the main error category', max_length=100, null=True, verbose_name='Sub Error Type'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Ticket created'), ('assigned', 'Ticket assigned'), ('replied', 'New reply'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('sla_risk', 'SLA at risk'), ('sla_breach', 'SLA breached'), ('escalated', 'Escalated'), ('mentioned', 'Mentioned')], max_length=40, verbose_name='Event')),
                ('title', models.CharField(help_text='Main line shown in the Windows toast', max_length=200, verbose_name='Title')),
                ('body', models.TextField(blank=True, help_text='Secondary line shown in the Windows toast', verbose_name='Body')),
                ('url', models.CharField(blank=True, help_text='Where to navigate when the toast is clicked', max_length=300, verbose_name='URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('emailed_at', models.DateTimeField(blank=True, help_text='Set when the email fallback has been sent', null=True, verbose_name='Emailed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('recipient', models.ForeignKey(help_text='User who should see this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('ticket', models.ForeignKey(blank=True, help_text='Ticket this notification relates to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='tickets_not_recipie_eda5c0_idx'), models.Index(fields=['recipient', 'id'], name='tickets_not_recipie_a2dd21_idx')],
            },
        ),
    ]
