# Generated by Django 5.0.14 on 2026-07-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
