# Generated by Django 5.0.14 on 2026-09-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_sub_error_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket was archived', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archived_by',
            field=models.CharField(blank=True, default='', help_text="Username or 'System (auto)'", max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from active lists, kept in database'),
        ),
    ]
