# Generated by Django 5.0.14 on 2026-07-25 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_employeemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.department')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.unit')),
            ],
            options={
                'verbose_name': 'Department Credential',
                'verbose_name_plural': 'Department Credentials',
                'ordering': ['unit__code', 'department__name'],
                'unique_together': {('unit', 'department')},
            },
        ),
    ]
