# Generated by Django 5.0.14 on 2026-09-21 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_archived_at_ticket_archived_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTypeMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Roadmap Error, GPL Error', max_length=100, unique=True, verbose_name='Main Error Type')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in dropdowns')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive types do not appear in the Close Ticket dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Main Error Type',
                'verbose_name_plural': 'Main Error Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='settingsauditlog',
            name='setting_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee'), ('CREDENTIAL', 'Credential'), ('CONTACT', 'Contact'), ('EMAIL', 'Email'), ('PASSWORD', 'Password'), ('SCREEN', 'Screen'), ('ERROR_TYPE', 'Error Type'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='main_error_type',
            field=models.CharField(blank=True, help_text='Selected when closing the ticket (from Error Type Master)', max_length=50, null=True, verbose_name='Main Error Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sub_error_type',
            field=models.CharField(blank=True, help_text='Selected when closing the ticket (from Error Type Master)', max_length=150, null=True, verbose_name='Sub Error Type'),
        ),
        migrations.CreateModel(
            name='ErrorTypeSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Database Error, User / Data Entry Error', max_length=150, verbose_name='Sub Error Type')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in dropdowns')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive types do not appear in the Close Ticket dropdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='tickets.errortypemain', verbose_name='Parent Main Error Type')),
            ],
            options={
                'verbose_name': 'Sub Error Type',
                'verbose_name_plural': 'Sub Error Types',
                'ordering': ['main__display_order', 'display_order', 'name'],
                'unique_together': {('main', 'name')},
            },
        ),
    ]
