# Generated by Django 5.0.14 on 2026-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_departmentcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='can_assign_ticket',
            field=models.BooleanField(default=False, help_text='Enable if this employee can be assigned tickets to other employees', verbose_name='Can Assign Tickets'),
        ),
    ]
