# Generated by Django 5.0.14 on 2026-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_viewed',
            field=models.BooleanField(default=False, help_text='Admin has viewed this ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Notification email has been sent to admin'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='viewed_at',
            field=models.DateTimeField(blank=True, help_text='When the ticket was first viewed by admin', null=True),
        ),
    ]
