# Generated by Django 5.0.14 on 2026-08-07 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_is_viewed_ticket_notification_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by_name', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('TOGGLE', 'Toggled'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('setting_type', models.CharField(choices=[('UNIT', 'Unit'), ('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee'), ('CREDENTIAL', 'Credential'), ('CONTACT', 'Contact'), ('EMAIL', 'Email'), ('PASSWORD', 'Password'), ('GENERAL', 'General')], max_length=20)),
                ('setting_name', models.CharField(max_length=200)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settings Audit Log',
                'verbose_name_plural': 'Settings Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
