# Generated by Django 5.0.14 on 2026-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_settingsauditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='attachment',
            new_name='attachment_1',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
