# Generated by Django 5.0.14 on 2026-08-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_rename_attachment_ticket_attachment_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='main_error_type',
            field=models.CharField(blank=True, choices=[('Roadmap Error', 'Roadmap Error'), ('GPL Error', 'GPL Error')], help_text='Select the main error category when closing the ticket', max_length=50, null=True, verbose_name='Main Error Type'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sub_error_type',
            field=models.CharField(blank=True, help_text='Select the sub-error type based on the main error category', max_length=100, null=True, verbose_name='Sub Error Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='error_type',
            field=models.CharField(choices=[('New', 'New'), ('Repeated', 'Repeated')], default='New', max_length=50, verbose_name='Error Type'),
        ),
    ]
