# Generated by Django 5.0.14 on 2026-08-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_ticket_main_error_type_ticket_sub_error_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERPHolderMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_user_id', models.CharField(db_index=True, help_text='ERP User ID (e.g., 0001, 0002)', max_length=50, verbose_name='ERP User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(help_text='Employee mapped to this ERP User ID', on_delete=django.db.models.deletion.CASCADE, related_name='erp_mappings', to='tickets.employeemaster', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'ERP User ID Mapping',
                'verbose_name_plural': 'ERP User ID Mappings',
                'ordering': ['erp_user_id', 'employee__employee_id'],
                'indexes': [models.Index(fields=['erp_user_id'], name='tickets_erp_erp_use_ddb6fb_idx'), models.Index(fields=['employee'], name='tickets_erp_employe_b4edd0_idx')],
                'unique_together': {('erp_user_id', 'employee')},
            },
        ),
    ]
