# Generated by Django 5.0.14 on 2026-08-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_erpholdermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(help_text='Full name of the screen/module (e.g., Sales Order Entry)', max_length=150, unique=True, verbose_name='Screen Name')),
                ('screen_code', models.CharField(help_text='Short code for the screen (e.g., SO-001)', max_length=50, unique=True, verbose_name='Screen Code')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Screen Master',
                'verbose_name_plural': 'Screen Masters',
                'ordering': ['screen_name'],
            },
        ),
        migrations.AlterField(
            model_name='settingsauditlog',
            name='setting_type',
            field=models.CharField(choices=[('UNIT', 'Unit'), ('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee'), ('CREDENTIAL', 'Credential'), ('CONTACT', 'Contact'), ('EMAIL', 'Email'), ('PASSWORD', 'Password'), ('SCREEN', 'Screen'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScreenMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_user_id', models.CharField(db_index=True, help_text='ERP User ID (links to ERPHolderMapping.erp_user_id)', max_length=50, verbose_name='ERP User ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_mappings', to='tickets.screenmaster', verbose_name='Screen')),
            ],
            options={
                'verbose_name': 'Screen Mapping',
                'verbose_name_plural': 'Screen Mappings',
                'ordering': ['erp_user_id', 'screen__screen_name'],
                'indexes': [models.Index(fields=['erp_user_id'], name='tickets_scr_erp_use_e7c18a_idx'), models.Index(fields=['screen'], name='tickets_scr_screen__914ef2_idx')],
                'unique_together': {('screen', 'erp_user_id')},
            },
        ),
    ]
