# Generated by Django 5.0.14 on 2026-08-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_screenmaster_screenmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmaster',
            name='screen_type',
            field=models.CharField(choices=[('ALL', 'General'), ('ENTRY', 'Data Entry'), ('CONFIGURATION', 'Configuration'), ('QUERY', 'Report/Query')], default='ALL', help_text='The category of the screen', max_length=20, verbose_name='Screen Type'),
        ),
    ]
