# Generated by Django 5.0.14 on 2026-08-21 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_screenmaster_screen_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('reports', models.JSONField(default=list)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('send_time', models.TimeField(default='08:00')),
                ('send_unit_heads', models.BooleanField(default=True)),
                ('send_admins', models.BooleanField(default=True)),
                ('additional_emails', models.TextField(blank=True, default='')),
                ('all_units', models.BooleanField(default=True)),
                ('subject_template', models.CharField(default='Ticket Report - {{date}}', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('units', models.ManyToManyField(blank=True, related_name='email_schedules', to='tickets.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='tickets.unit')),
            ],
        ),
    ]
