# Generated by Django 5.0.14 on 2026-08-22 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_email_schedule_multiple_frequencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReopenAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/reopen/')),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reopen_attachments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
