# Generated by Django 5.0.14 on 2026-08-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_reopenattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
