# Generated by Django 5.0.14 on 2026-08-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_employeemaster_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
