# Generated by Django 5.0.14 on 2026-08-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_unithead_created_at_unithead_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpholdermapping',
            options={'ordering': ['erp_user_id'], 'verbose_name': 'ERP User ID', 'verbose_name_plural': 'ERP User IDs'},
        ),
        migrations.AlterUniqueTogether(
            name='erpholdermapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='erpholdermapping',
            name='is_mapped',
            field=models.BooleanField(default=False, help_text='True if this ERP ID is mapped to an employee', verbose_name='Is Mapped'),
        ),
        migrations.AlterField(
            model_name='erpholdermapping',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee mapped to this ERP User ID (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erp_mappings', to='tickets.employeemaster', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='erpholdermapping',
            name='erp_user_id',
            field=models.CharField(db_index=True, help_text='ERP User ID (e.g., 0001, 0002, HRD1223)', max_length=50, unique=True, verbose_name='ERP User ID'),
        ),
        migrations.AddIndex(
            model_name='erpholdermapping',
            index=models.Index(fields=['is_mapped'], name='tickets_erp_is_mapp_c70d3e_idx'),
        ),
    ]
